server:
  port: 7001
eureka:
  instance:
    hostname: 192.168.1.4 #eureka服务端实例名称 localhost
  client:
    fetch-registry: false #表示不想注册中心注册自己
    register-with-eureka: false #表示自己就是注册中心，职责就是维护服务实例，比不要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka #设置与Eureka Server交互的地址地址查询服务和注册服务都需要这个地址
      defaultZone: http://192.168.1.5:7001/eureka,http://192.168.1.4:7001/eureka #http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka