server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml        # mybatis配置文件所在路径
  type-aliases-package: cn.zhangguimin.entitys    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: SpringCloud-empt
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/ssm_crud_03              # 数据库名称
    username: root
    password: 1991820
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 2000                                  # 等待连接获取的最大超时时间
#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: SpringCloud-empt8003
    prefer-ip-address: true
info:
  app.name: SpringCloud-empt
  company.name: www.zhangguimin.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$